apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: mynewapp
spec:
  containers:
  - name: mywebapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-svc
spec:
  selector:
    name: mynewapp
  ports:
  - port: 80
    targetPort: 80


